# Generated by Django 5.1.1 on 2024-12-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_researchfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='research',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='research_images/'),
        ),
        migrations.AddField(
            model_name='research',
            name='kml_file',
            field=models.FileField(blank=True, null=True, upload_to='research_kml_files/'),
        ),
    ]
