# Generated by Django 5.1.1 on 2024-12-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_research_updated_at_research_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_date', models.DateTimeField()),
                ('defect_name', models.CharField(max_length=255)),
                ('defect_description', models.TextField()),
                ('defect_coordinates', models.CharField(max_length=255)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='myapp.research')),
            ],
        ),
    ]
