# Generated by Django 5.1.1 on 2024-12-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_defect'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='defect_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
