# Generated by Django 5.2 on 2025-05-08 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_news_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defect",
            name="defect_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
