# Generated by Django 5.1.1 on 2025-05-08 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_defect_defect_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kml_file', models.FileField(upload_to='research_routes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinates', models.TextField(blank=True, null=True)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='myapp.research')),
            ],
        ),
    ]
