# Generated by Django 5.1.3 on 2025-05-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_forummessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="distance",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Расстояние (м)"
            ),
        ),
    ]
